apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  DSN: {{ .Values.connectionstring | b64enc | quote }}
  root.crt: {{. Values.caCert | b64enc | quote }}
